"""sync schema baseline

Revision ID: ed628a533673
Revises: f2a3b4c5d6e7
Create Date: 2026-08-02 15:58:48.918293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed628a533673'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=200), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_documents_device_id'), 'ai_knowledge_documents', ['device_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_documents_doc_type'), 'ai_knowledge_documents', ['doc_type'], unique=False)
    op.create_table('compliance_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('config_source', sa.String(length=50), nullable=True),
    sa.Column('config_text', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.Column('audit_mode', sa.String(length=20), nullable=True),
    sa.Column('ai_provider', sa.String(length=20), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('result_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_standards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_ids_json', sa.Text(), nullable=True),
    sa.Column('change_request_id', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_device_id'), 'jobs', ['device_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user'), 'notifications', ['user'], unique=False)
    op.create_table('service_slo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_key', sa.String(length=50), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('slo_target', sa.DECIMAL(precision=7, scale=4), nullable=False),
    sa.Column('device_types', sa.String(length=200), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_slo_is_active'), 'service_slo', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_slo_service_key'), 'service_slo', ['service_key'], unique=True)
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('check_logic', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['standard_id'], ['compliance_standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_standard_id'), 'compliance_rules', ['standard_id'], unique=False)
    op.create_table('deploy_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('target_devices', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('total_devices', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('deploy_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['deploy_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_history_created_at'), 'deploy_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_deploy_history_operation_type'), 'deploy_history', ['operation_type'], unique=False)
    op.create_index(op.f('ix_deploy_history_user_id'), 'deploy_history', ['user_id'], unique=False)
    op.create_table('device_interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('if_name', sa.String(length=100), nullable=True),
    sa.Column('if_descr', sa.String(length=200), nullable=True),
    sa.Column('oper_status', sa.String(length=20), nullable=True),
    sa.Column('admin_status', sa.String(length=20), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('is_uplink', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('monitored', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('peer_device_id', sa.Integer(), nullable=True),
    sa.Column('peer_device_name', sa.String(length=200), nullable=True),
    sa.Column('peer_ip', sa.String(length=64), nullable=True),
    sa.Column('peer_if_name', sa.String(length=100), nullable=True),
    sa.Column('neighbor_source', sa.String(length=20), nullable=True),
    sa.Column('neighbor_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_in_bps', sa.BigInteger(), nullable=True),
    sa.Column('last_out_bps', sa.BigInteger(), nullable=True),
    sa.Column('last_in_util', sa.Float(), nullable=True),
    sa.Column('last_out_util', sa.Float(), nullable=True),
    sa.Column('last_in_errors', sa.BigInteger(), nullable=True),
    sa.Column('last_out_errors', sa.BigInteger(), nullable=True),
    sa.Column('last_in_octets', sa.BigInteger(), nullable=True),
    sa.Column('last_out_octets', sa.BigInteger(), nullable=True),
    sa.Column('last_sample_at', sa.DateTime(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'if_index', name='uq_device_if_index')
    )
    op.create_index(op.f('ix_device_interfaces_device_id'), 'device_interfaces', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_interfaces_if_name'), 'device_interfaces', ['if_name'], unique=False)
    op.create_index(op.f('ix_device_interfaces_is_uplink'), 'device_interfaces', ['is_uplink'], unique=False)
    op.create_index(op.f('ix_device_interfaces_monitored'), 'device_interfaces', ['monitored'], unique=False)
    op.create_index(op.f('ix_device_interfaces_peer_device_id'), 'device_interfaces', ['peer_device_id'], unique=False)
    op.create_table('device_ports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('port_type', sa.String(length=20), nullable=True),
    sa.Column('anchor_x', sa.Float(), nullable=True),
    sa.Column('anchor_y', sa.Float(), nullable=True),
    sa.Column('is_auto_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_ports_device_id'), 'device_ports', ['device_id'], unique=False)
    op.create_table('deploy_device_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deploy_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rollback_available', sa.Boolean(), nullable=True),
    sa.Column('rollback_status', sa.String(length=20), nullable=True),
    sa.Column('cli_output', sa.Text(), nullable=True),
    sa.Column('diff_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deploy_id'], ['deploy_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploy_device_results_deploy_id'), 'deploy_device_results', ['deploy_id'], unique=False)
    op.create_index(op.f('ix_deploy_device_results_device_id'), 'deploy_device_results', ['device_id'], unique=False)
    op.create_table('interface_traffic_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('in_bps', sa.BigInteger(), nullable=True),
    sa.Column('out_bps', sa.BigInteger(), nullable=True),
    sa.Column('in_util', sa.Float(), nullable=True),
    sa.Column('out_util', sa.Float(), nullable=True),
    sa.Column('in_errors', sa.BigInteger(), nullable=True),
    sa.Column('out_errors', sa.BigInteger(), nullable=True),
    sa.Column('oper_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['device_interfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_iface_sample_iface_ts', 'interface_traffic_samples', ['interface_id', 'ts'], unique=False)
    op.create_index(op.f('ix_interface_traffic_samples_device_id'), 'interface_traffic_samples', ['device_id'], unique=False)
    op.create_index(op.f('ix_interface_traffic_samples_interface_id'), 'interface_traffic_samples', ['interface_id'], unique=False)
    op.create_index(op.f('ix_interface_traffic_samples_ts'), 'interface_traffic_samples', ['ts'], unique=False)
    op.create_table('topo_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_plan_id', sa.Integer(), nullable=False),
    sa.Column('node_kind', sa.String(length=20), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('x_percent', sa.Float(), nullable=True),
    sa.Column('y_percent', sa.Float(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('junction_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['device_ports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topo_nodes_floor_plan_id'), 'topo_nodes', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_topo_nodes_port_id'), 'topo_nodes', ['port_id'], unique=False)
    op.create_table('spare_part_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('in_stock_at', sa.DateTime(), nullable=True),
    sa.Column('out_at', sa.DateTime(), nullable=True),
    sa.Column('installed_device_id', sa.Integer(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('installed_by', sa.String(length=100), nullable=True),
    sa.Column('removed_from_device_id', sa.Integer(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('out_to_maintenance', sa.Integer(), nullable=True),
    sa.Column('out_to_task', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['installed_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['out_to_maintenance'], ['maintenance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['out_to_task'], ['maintenance_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['part_id'], ['spare_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_from_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_part_instances_part_id'), 'spare_part_instances', ['part_id'], unique=False)
    op.create_index(op.f('ix_spare_part_instances_po_number'), 'spare_part_instances', ['po_number'], unique=False)
    op.create_index(op.f('ix_spare_part_instances_serial_number'), 'spare_part_instances', ['serial_number'], unique=True)
    op.create_index(op.f('ix_spare_part_instances_status'), 'spare_part_instances', ['status'], unique=False)
    op.create_table('topo_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_plan_id', sa.Integer(), nullable=False),
    sa.Column('a_node_id', sa.Integer(), nullable=False),
    sa.Column('b_node_id', sa.Integer(), nullable=False),
    sa.Column('cable_type', sa.String(length=20), nullable=True),
    sa.Column('waypoints', sa.Text(), nullable=True),
    sa.Column('length_weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('cable_name', sa.String(length=50), nullable=True),
    sa.Column('cable_id', sa.Integer(), nullable=True),
    sa.Column('cable_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['a_node_id'], ['topo_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['b_node_id'], ['topo_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topo_edges_a_node_id'), 'topo_edges', ['a_node_id'], unique=False)
    op.create_index(op.f('ix_topo_edges_b_node_id'), 'topo_edges', ['b_node_id'], unique=False)
    op.create_index(op.f('ix_topo_edges_cable_id'), 'topo_edges', ['cable_id'], unique=False)
    op.create_index(op.f('ix_topo_edges_floor_plan_id'), 'topo_edges', ['floor_plan_id'], unique=False)
    op.create_index(op.f('ix_topo_edges_status'), 'topo_edges', ['status'], unique=False)
    op.create_table('device_spare_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('spare_instance_id', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('part_name', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('installed_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('removed_by', sa.String(length=100), nullable=True),
    sa.Column('removal_reason', sa.String(length=200), nullable=True),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spare_instance_id'], ['spare_part_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_spare_relations_device_id'), 'device_spare_relations', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_spare_relations_spare_instance_id'), 'device_spare_relations', ['spare_instance_id'], unique=False)
    op.create_index(op.f('ix_device_spare_relations_status'), 'device_spare_relations', ['status'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_operator', 'audit_logs', ['operator'], unique=False)
    op.add_column('device_nodes', sa.Column('scale', sa.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('devices', sa.Column('deployment_status', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('reachability', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('last_reachability_check', sa.DateTime(), nullable=True))
    op.add_column('devices', sa.Column('reachability_latency_ms', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('reachability_method', sa.String(length=20), nullable=True))
    op.add_column('devices', sa.Column('monitor_tier', sa.String(length=20), nullable=True))
    op.add_column('devices', sa.Column('snmp_enabled', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('devices', sa.Column('snmp_version', sa.String(length=10), nullable=True))
    op.add_column('devices', sa.Column('snmp_community', sa.String(length=200), nullable=True))
    op.add_column('devices', sa.Column('snmp_port', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_deployment_status'), 'devices', ['deployment_status'], unique=False)
    op.create_index(op.f('ix_devices_monitor_tier'), 'devices', ['monitor_tier'], unique=False)
    op.create_index(op.f('ix_devices_reachability'), 'devices', ['reachability'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    op.add_column('fault_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('assigned_to', sa.String(length=100), nullable=True))
    op.add_column('fault_records', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('accepted_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('diagnosing_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('transferred_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('fault_type', sa.String(length=20), nullable=True))
    op.add_column('fault_records', sa.Column('diagnosis_text', sa.Text(), nullable=True))
    op.add_column('fault_records', sa.Column('diagnosis_result', sa.String(length=50), nullable=True))
    op.add_column('fault_records', sa.Column('ai_analysis_result', sa.Text(), nullable=True))
    op.add_column('fault_records', sa.Column('ai_root_cause', sa.Text(), nullable=True))
    op.add_column('fault_records', sa.Column('ai_recommendation', sa.String(length=50), nullable=True))
    op.add_column('fault_records', sa.Column('ai_confidence', sa.DECIMAL(precision=3, scale=2), nullable=True))
    op.add_column('fault_records', sa.Column('incident_type', sa.String(length=20), nullable=True))
    op.add_column('fault_records', sa.Column('auto_created_maintenance', sa.Boolean(), nullable=True))
    op.add_column('fault_records', sa.Column('source_type', sa.String(length=30), nullable=True))
    op.add_column('fault_records', sa.Column('source_key', sa.String(length=200), nullable=True))
    op.add_column('fault_records', sa.Column('source_event', sa.String(length=50), nullable=True))
    op.add_column('fault_records', sa.Column('if_index', sa.Integer(), nullable=True))
    op.add_column('fault_records', sa.Column('if_name', sa.String(length=100), nullable=True))
    op.add_column('fault_records', sa.Column('peer_device_id', sa.Integer(), nullable=True))
    op.add_column('fault_records', sa.Column('peer_if_name', sa.String(length=100), nullable=True))
    op.add_column('fault_records', sa.Column('event_count', sa.Integer(), nullable=True))
    op.add_column('fault_records', sa.Column('last_event_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('fault_records', sa.Column('assigned_email', sa.String(length=200), nullable=True))
    op.add_column('fault_records', sa.Column('review_required', sa.Boolean(), server_default='1', nullable=True))
    op.add_column('fault_records', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('fault_records', sa.Column('reviewed_by', sa.String(length=100), nullable=True))
    op.add_column('fault_records', sa.Column('false_positive', sa.Boolean(), server_default='0', nullable=True))
    op.create_index(op.f('ix_fault_records_assigned_to'), 'fault_records', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_fault_records_source_event'), 'fault_records', ['source_event'], unique=False)
    op.create_index(op.f('ix_fault_records_source_key'), 'fault_records', ['source_key'], unique=False)
    op.create_index(op.f('ix_fault_records_source_type'), 'fault_records', ['source_type'], unique=False)
    op.create_foreign_key('fault_records_maintenance_id_fkey', 'fault_records', 'maintenance_records', ['maintenance_id'], ['id'], ondelete='SET NULL')
    op.add_column('maintenance_records', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('maintenance_records', sa.Column('problem_description', sa.Text(), nullable=True))
    op.add_column('maintenance_records', sa.Column('solution', sa.Text(), nullable=True))
    op.add_column('maintenance_records', sa.Column('technician', sa.String(length=100), nullable=True))
    op.add_column('maintenance_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('maintenance_records', sa.Column('auto_created', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('maintenance_records', sa.Column('ai_recommended', sa.Boolean(), server_default='0', nullable=True))
    op.create_foreign_key('maintenance_records_fault_id_fkey', 'maintenance_records', 'fault_records', ['fault_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('maintenance_tasks_maintenance_id_fkey', 'maintenance_tasks', type_='foreignkey')
    op.create_foreign_key('maintenance_tasks_maintenance_id_fkey', 'maintenance_tasks', 'maintenance_records', ['maintenance_id'], ['id'], ondelete='SET NULL')
    op.add_column('spare_part_movements', sa.Column('po_number', sa.String(length=100), nullable=True))
    op.add_column('spare_part_movements', sa.Column('session_code', sa.String(length=20), nullable=True))
    op.add_column('spare_part_movements', sa.Column('target_device_id', sa.Integer(), nullable=True))
    op.add_column('spare_part_movements', sa.Column('source_device_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_spare_part_movements_session_code'), 'spare_part_movements', ['session_code'], unique=False)
    op.create_foreign_key('spare_part_movements_target_device_id_fkey', 'spare_part_movements', 'devices', ['target_device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('spare_part_movements_source_device_id_fkey', 'spare_part_movements', 'devices', ['source_device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spare_part_movements_source_device_id_fkey', 'spare_part_movements', type_='foreignkey')
    op.drop_constraint('spare_part_movements_target_device_id_fkey', 'spare_part_movements', type_='foreignkey')
    op.drop_index(op.f('ix_spare_part_movements_session_code'), table_name='spare_part_movements')
    op.drop_column('spare_part_movements', 'source_device_id')
    op.drop_column('spare_part_movements', 'target_device_id')
    op.drop_column('spare_part_movements', 'session_code')
    op.drop_column('spare_part_movements', 'po_number')
    op.drop_constraint('maintenance_tasks_maintenance_id_fkey', 'maintenance_tasks', type_='foreignkey')
    op.create_foreign_key('maintenance_tasks_maintenance_id_fkey', 'maintenance_tasks', 'maintenance_records', ['maintenance_id'], ['id'])
    op.drop_constraint('maintenance_records_fault_id_fkey', 'maintenance_records', type_='foreignkey')
    op.drop_column('maintenance_records', 'ai_recommended')
    op.drop_column('maintenance_records', 'auto_created')
    op.drop_column('maintenance_records', 'updated_at')
    op.drop_column('maintenance_records', 'technician')
    op.drop_column('maintenance_records', 'solution')
    op.drop_column('maintenance_records', 'problem_description')
    op.drop_column('maintenance_records', 'title')
    op.drop_constraint('fault_records_maintenance_id_fkey', 'fault_records', type_='foreignkey')
    op.drop_index(op.f('ix_fault_records_source_type'), table_name='fault_records')
    op.drop_index(op.f('ix_fault_records_source_key'), table_name='fault_records')
    op.drop_index(op.f('ix_fault_records_source_event'), table_name='fault_records')
    op.drop_index(op.f('ix_fault_records_assigned_to'), table_name='fault_records')
    op.drop_column('fault_records', 'false_positive')
    op.drop_column('fault_records', 'reviewed_by')
    op.drop_column('fault_records', 'reviewed_at')
    op.drop_column('fault_records', 'review_required')
    op.drop_column('fault_records', 'assigned_email')
    op.drop_column('fault_records', 'recommendation')
    op.drop_column('fault_records', 'last_event_at')
    op.drop_column('fault_records', 'event_count')
    op.drop_column('fault_records', 'peer_if_name')
    op.drop_column('fault_records', 'peer_device_id')
    op.drop_column('fault_records', 'if_name')
    op.drop_column('fault_records', 'if_index')
    op.drop_column('fault_records', 'source_event')
    op.drop_column('fault_records', 'source_key')
    op.drop_column('fault_records', 'source_type')
    op.drop_column('fault_records', 'auto_created_maintenance')
    op.drop_column('fault_records', 'incident_type')
    op.drop_column('fault_records', 'ai_confidence')
    op.drop_column('fault_records', 'ai_recommendation')
    op.drop_column('fault_records', 'ai_root_cause')
    op.drop_column('fault_records', 'ai_analysis_result')
    op.drop_column('fault_records', 'diagnosis_result')
    op.drop_column('fault_records', 'diagnosis_text')
    op.drop_column('fault_records', 'fault_type')
    op.drop_column('fault_records', 'closed_at')
    op.drop_column('fault_records', 'resolved_at')
    op.drop_column('fault_records', 'transferred_at')
    op.drop_column('fault_records', 'diagnosing_at')
    op.drop_column('fault_records', 'accepted_at')
    op.drop_column('fault_records', 'assigned_at')
    op.drop_column('fault_records', 'assigned_to')
    op.drop_column('fault_records', 'updated_at')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_reachability'), table_name='devices')
    op.drop_index(op.f('ix_devices_monitor_tier'), table_name='devices')
    op.drop_index(op.f('ix_devices_deployment_status'), table_name='devices')
    op.drop_column('devices', 'snmp_port')
    op.drop_column('devices', 'snmp_community')
    op.drop_column('devices', 'snmp_version')
    op.drop_column('devices', 'snmp_enabled')
    op.drop_column('devices', 'monitor_tier')
    op.drop_column('devices', 'reachability_method')
    op.drop_column('devices', 'reachability_latency_ms')
    op.drop_column('devices', 'last_reachability_check')
    op.drop_column('devices', 'reachability')
    op.drop_column('devices', 'deployment_status')
    op.drop_column('device_nodes', 'scale')
    op.drop_index('ix_audit_logs_operator', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_device_spare_relations_status'), table_name='device_spare_relations')
    op.drop_index(op.f('ix_device_spare_relations_spare_instance_id'), table_name='device_spare_relations')
    op.drop_index(op.f('ix_device_spare_relations_device_id'), table_name='device_spare_relations')
    op.drop_table('device_spare_relations')
    op.drop_index(op.f('ix_topo_edges_status'), table_name='topo_edges')
    op.drop_index(op.f('ix_topo_edges_floor_plan_id'), table_name='topo_edges')
    op.drop_index(op.f('ix_topo_edges_cable_id'), table_name='topo_edges')
    op.drop_index(op.f('ix_topo_edges_b_node_id'), table_name='topo_edges')
    op.drop_index(op.f('ix_topo_edges_a_node_id'), table_name='topo_edges')
    op.drop_table('topo_edges')
    op.drop_index(op.f('ix_spare_part_instances_status'), table_name='spare_part_instances')
    op.drop_index(op.f('ix_spare_part_instances_serial_number'), table_name='spare_part_instances')
    op.drop_index(op.f('ix_spare_part_instances_po_number'), table_name='spare_part_instances')
    op.drop_index(op.f('ix_spare_part_instances_part_id'), table_name='spare_part_instances')
    op.drop_table('spare_part_instances')
    op.drop_index(op.f('ix_topo_nodes_port_id'), table_name='topo_nodes')
    op.drop_index(op.f('ix_topo_nodes_floor_plan_id'), table_name='topo_nodes')
    op.drop_table('topo_nodes')
    op.drop_index(op.f('ix_interface_traffic_samples_ts'), table_name='interface_traffic_samples')
    op.drop_index(op.f('ix_interface_traffic_samples_interface_id'), table_name='interface_traffic_samples')
    op.drop_index(op.f('ix_interface_traffic_samples_device_id'), table_name='interface_traffic_samples')
    op.drop_index('idx_iface_sample_iface_ts', table_name='interface_traffic_samples')
    op.drop_table('interface_traffic_samples')
    op.drop_index(op.f('ix_deploy_device_results_device_id'), table_name='deploy_device_results')
    op.drop_index(op.f('ix_deploy_device_results_deploy_id'), table_name='deploy_device_results')
    op.drop_table('deploy_device_results')
    op.drop_index(op.f('ix_device_ports_device_id'), table_name='device_ports')
    op.drop_table('device_ports')
    op.drop_index(op.f('ix_device_interfaces_peer_device_id'), table_name='device_interfaces')
    op.drop_index(op.f('ix_device_interfaces_monitored'), table_name='device_interfaces')
    op.drop_index(op.f('ix_device_interfaces_is_uplink'), table_name='device_interfaces')
    op.drop_index(op.f('ix_device_interfaces_if_name'), table_name='device_interfaces')
    op.drop_index(op.f('ix_device_interfaces_device_id'), table_name='device_interfaces')
    op.drop_table('device_interfaces')
    op.drop_index(op.f('ix_deploy_history_user_id'), table_name='deploy_history')
    op.drop_index(op.f('ix_deploy_history_operation_type'), table_name='deploy_history')
    op.drop_index(op.f('ix_deploy_history_created_at'), table_name='deploy_history')
    op.drop_table('deploy_history')
    op.drop_index(op.f('ix_compliance_rules_standard_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_service_slo_service_key'), table_name='service_slo')
    op.drop_index(op.f('ix_service_slo_is_active'), table_name='service_slo')
    op.drop_table('service_slo')
    op.drop_index(op.f('ix_notifications_user'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_device_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('compliance_standards')
    op.drop_table('compliance_audit_logs')
    op.drop_index(op.f('ix_ai_knowledge_documents_doc_type'), table_name='ai_knowledge_documents')
    op.drop_index(op.f('ix_ai_knowledge_documents_device_id'), table_name='ai_knowledge_documents')
    op.drop_table('ai_knowledge_documents')
    op.drop_table('ai_configs')
    # ### end Alembic commands ###
